engines:
  rubocop:
    enabled: true
    config:
      file: .rubocop.yml
    exclude_paths:
      - 'vendor/'
      - 'db/'

exclude_paths:
  - 'db/'

ratings:
  paths:
    - 'app/**/*'
    - 'lib/**/*'
    - '**.rb'
